export const cardData = [
  {
    id: 0,
    imageURL:
      "https://images.pexels.com/photos/3342697/pexels-photo-3342697.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    cardTitle: "Wedding-Package",
    packageName: "Wedding-Package",
    dailyRate: "₹5000",
    packageContents: "Sample package contents ",
    optionalPakageContents: "Sample package photos",
    eventRate: "₹30000",
    hourlyRate: "₹1000",
    packageCategory: "Wedding",
  },
  {
    id: 1,
    imageURL:
      "https://cdn.pixabay.com/photo/2017/05/23/22/33/birthday-2338813_960_720.jpg",
    cardTitle: "Birthday-Package",
    packageName: "Birthday",
    dailyRate: "₹4000",
    packageContents: "Sample birthday package",
    optionalPakageContents: "Sample birthday package",
    eventRate: "₹50000",
    hourlyRate: "₹3000",
    packageCategory: "Babies and Kids",
  },
  {
    id: 2,
    imageURL:
      "https://cdn.pixabay.com/photo/2017/02/20/00/02/wedding-2081269_960_720.jpg",
    cardTitle: "Special Occasion-Package",
    packageName: "Special Occasion",
    dailyRate: "₹2000",
    packageContents: "Sample Special Occasion package",
    optionalPakageContents: "Sample Special Occasion package",
    eventRate: "₹40000",
    hourlyRate: "₹2500",
    packageCategory: "Special Occasion",
  },
  {
    id: 3,
    imageURL:
      "https://cdn.pixabay.com/photo/2017/03/13/17/26/ecommerce-2140603_960_720.jpg",
    cardTitle: "Commercial-Package",
    packageName: "Commercial",
    dailyRate: "₹2500",
    packageContents: "Sample Commercial-Package ",
    optionalPakageContents: "Sample Commercial-Package ",
    eventRate: "₹40000",
    hourlyRate: "₹2500",
    packageCategory: "Commercial",
  },
  {
    id: 4,
    imageURL:
      "https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_960_720.jpg",
    cardTitle: "Nature-Package",
    packageName: "Nature",
    dailyRate: "₹2500",
    packageContents: "Sample Nature-Package",
    optionalPakageContents: "Sample Nature-Package",
    eventRate: "₹45000",
    hourlyRate: "₹2560",
    packageCategory: "Nature",
  },
  {
    id: 5,
    imageURL:
      "https://cdn.pixabay.com/photo/2017/06/21/02/20/fashion-2425755_960_720.jpg",
    cardTitle: "Fashion and Portfolio-Package",
    packageName: "Fashion and Portfolio",
    dailyRate: "₹4000",
    packageContents: "Sample Fashion and Portfolio Package",
    optionalPakageContents: "Sample Fashion and Portfolio Package ",
    eventRate: "₹45000",
    hourlyRate: "₹2560",
    packageCategory: "Fashion and Portfolio",
  },
  {
    id: 6,
    imageURL:
      "https://cdn.pixabay.com/photo/2017/08/06/20/11/wedding-2595862_960_720.jpg",
    cardTitle: "Wedding-Package",
    packageName: "Wedding-Package",
    dailyRate: "₹5000",
    packageContents: "Sample package contents ",
    optionalPakageContents: "Sample package photos",
    eventRate: "₹30000",
    hourlyRate: "₹1000",
    packageCategory: "Wedding",
  },
  {
    id: 7,
    imageURL:
      "https://cdn.pixabay.com/photo/2016/05/17/22/16/baby-1399332_960_720.jpg",
    cardTitle: "Babies and Kids-Package",
    packageName: "Birthday",
    dailyRate: "₹4000",
    packageContents: "Sample birthday package",
    optionalPakageContents: "Sample birthday package",
    eventRate: "₹50000",
    hourlyRate: "₹3000",
    packageCategory: "Babies and Kids",
  },
];
